# Setup
#title:        Project or Site name
title:        iotac's blog
#tagline:      A responsive theme for your project on GitHub Pages
tagline:      Wir müssen wissen, wir werden wissen.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
#name:       Author name
    name:       iotac
#url:        http://yourhomepage.com 
    url:        https://blog.iotac.xyz/about

# Gems
gems:
  - jekyll-paginate

# Plugins
plugins:
  - jekyll-sitemap

#Others
markdown: kramdown
